### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [hiik3n/RubyonRails_myBlog#1]
Hi @hiik3n,

Thanks for your submitting. Good work 👍
I see that you have finish required stories. We still have time for this weekend, you can implement others features, try to deploy it to Heroku and add more submissions. We will continue to review your work.

Excellent work, here are some suggestions so you can improve your blog:
- Add root path to your route file.
- When deploy to heroku, there are some issues with javascript ( for example remote delete doesn't work). It is a bug of Bootstrap 4 beta. To fix this, remember to add `//=require tether` in `application.js`.
- Good point to add boostrap, you can add it to all the pages (if have time)
- Think about how to improve search function so it don't care about uppercase or lowercase (hint: try to lowercase the search param before comparing)
- Always be cautious with user input, you can use Active Record Validations to validate (like required condition for article title).

We see that you haven't deployed your app to heroku yet. What is the issue you are facing? we can try to help. Keep up the good work!

**Comment by coderschoolreview** [comment]
Hi @hiik3n, good to see that you updated your submission. Looks like the heroku app is not working yet. Have you typed `git push heroku master`? Additional suggestions:
- Please use bootstrap styling to make your text box and form button look better (in your Edit page, for example)
- Try to write good Git messages http://chris.beams.io/posts/git-commit/
- Use tabs instead of spaces (in your Article model, for example). See more Ruby coding style guide at https://github.com/styleguide/ruby/coding-style
- Update your README accordingly

Your submission is still not complete. We are making final decisions by tomorrow so if you want to be considered again, please submit your updates ASAP and we look forward to seeing them.

**Comment by hiik3n** [comment]
Hi @coderschoolreview ,
I has tried the instruction in pre-work tutorial but it did not work (include push to heroku master)
Then I tried follow this for rails 5: https://devcenter.heroku.com/articles/getting-started-with-rails5
I met this error frequently (ENOTFOUND: getaddrinfo ENOTFOUND api.heroku.com api.heroku.com:443). However, sometime it worked.
Here is some log:

```
$ heroku logs
2016-10-06T01:40:12.352009+00:00 app[web.1]: * Environment: production
2016-10-06T01:40:12.352165+00:00 app[web.1]: * Listening on tcp://0.0.0.0:4653
2016-10-06T01:40:12.352524+00:00 app[web.1]: Use Ctrl-C to stop
2016-10-06T01:40:12.770328+00:00 heroku[web.1]: State changed from starting to up
2016-10-06T01:40:26.847092+00:00 heroku[api]: Starting process with command `bundle exec rake db:migrate` by hiik3n@gmail.com
2016-10-06T01:40:29.889967+00:00 heroku[run.9059]: Awaiting client
2016-10-06T01:40:29.918054+00:00 heroku[run.9059]: Starting process with command `bundle exec rake db:migrate`
2016-10-06T01:40:30.027222+00:00 heroku[run.9059]: State changed from starting to up
2016-10-06T01:40:34.393525+00:00 heroku[run.9059]: Process exited with status 0
2016-10-06T01:40:34.411787+00:00 heroku[run.9059]: State changed from up to complete
2016-10-06T01:41:04.448571+00:00 heroku[api]: Starting process with command `bash` by hiik3n@gmail.com
2016-10-06T01:41:07.251889+00:00 heroku[run.3468]: Awaiting client
2016-10-06T01:41:07.277809+00:00 heroku[run.3468]: Starting process with command `bash`
2016-10-06T01:41:07.375037+00:00 heroku[run.3468]: State changed from starting to up
2016-10-06T01:41:18.850287+00:00 heroku[router]: at=info method=GET path="/" host=fierce-harbor-81008.herokuapp.com request_id=30714dce-4a6c-4a28-86e5-f41e11d1d20c fwd="14.169.249.198" dyno=web.1 connect=1ms service=69ms status=404 bytes=1744
2016-10-06T01:41:18.828718+00:00 app[web.1]: I, [2016-10-06T01:41:18.828557 #3]  INFO -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] Started GET "/" for 14.169.249.198 at 2016-10-06 01:41:18 +0000
2016-10-06T01:41:18.831183+00:00 app[web.1]: F, [2016-10-06T01:41:18.831121 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c]   
2016-10-06T01:41:18.831257+00:00 app[web.1]: F, [2016-10-06T01:41:18.831194 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] ActionController::RoutingError (No route matches [GET] "/"):
2016-10-06T01:41:18.831338+00:00 app[web.1]: F, [2016-10-06T01:41:18.831261 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c]   
2016-10-06T01:41:18.831364+00:00 app[web.1]: F, [2016-10-06T01:41:18.831315 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
2016-10-06T01:41:18.831419+00:00 app[web.1]: F, [2016-10-06T01:41:18.831367 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2016-10-06T01:41:18.831472+00:00 app[web.1]: F, [2016-10-06T01:41:18.831418 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
2016-10-06T01:41:18.831577+00:00 app[web.1]: F, [2016-10-06T01:41:18.831528 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
2016-10-06T01:41:18.831525+00:00 app[web.1]: F, [2016-10-06T01:41:18.831470 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
2016-10-06T01:41:18.831633+00:00 app[web.1]: F, [2016-10-06T01:41:18.831579 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-10-06T01:41:18.831684+00:00 app[web.1]: F, [2016-10-06T01:41:18.831634 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
2016-10-06T01:41:18.831736+00:00 app[web.1]: F, [2016-10-06T01:41:18.831679 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
2016-10-06T01:41:18.831791+00:00 app[web.1]: F, [2016-10-06T01:41:18.831733 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2016-10-06T01:41:18.831866+00:00 app[web.1]: F, [2016-10-06T01:41:18.831795 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
2016-10-06T01:41:18.831919+00:00 app[web.1]: F, [2016-10-06T01:41:18.831870 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
2016-10-06T01:41:18.831971+00:00 app[web.1]: F, [2016-10-06T01:41:18.831921 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-10-06T01:41:18.832016+00:00 app[web.1]: F, [2016-10-06T01:41:18.831971 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
2016-10-06T01:41:18.832075+00:00 app[web.1]: F, [2016-10-06T01:41:18.832024 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
2016-10-06T01:41:18.832128+00:00 app[web.1]: F, [2016-10-06T01:41:18.832075 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
2016-10-06T01:41:18.832190+00:00 app[web.1]: F, [2016-10-06T01:41:18.832137 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
2016-10-06T01:41:18.832248+00:00 app[web.1]: F, [2016-10-06T01:41:18.832199 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
2016-10-06T01:41:18.832306+00:00 app[web.1]: F, [2016-10-06T01:41:18.832250 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
2016-10-06T01:41:18.832355+00:00 app[web.1]: F, [2016-10-06T01:41:18.832308 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
2016-10-06T01:41:18.832406+00:00 app[web.1]: F, [2016-10-06T01:41:18.832357 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
2016-10-06T01:41:18.848551+00:00 app[web.1]: F, [2016-10-06T01:41:18.832405 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
2016-10-06T01:41:18.848605+00:00 app[web.1]: F, [2016-10-06T01:41:18.848536 #3] FATAL -- : [30714dce-4a6c-4a28-86e5-f41e11d1d20c] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
2016-10-06T01:42:33.599015+00:00 heroku[run.3468]: Process exited with status 130
2016-10-06T01:42:33.595964+00:00 heroku[run.3468]: State changed from up to complete
2016-10-06T01:47:02.481335+00:00 heroku[api]: Deploy 26bf648 by hiik3n@gmail.com
2016-10-06T01:47:02.481435+00:00 heroku[api]: Release v9 created by hiik3n@gmail.com
2016-10-06T01:47:02.681487+00:00 heroku[slug-compiler]: Slug compilation started
2016-10-06T01:47:02.681496+00:00 heroku[slug-compiler]: Slug compilation finished
2016-10-06T01:47:02.745799+00:00 heroku[web.1]: Restarting
2016-10-06T01:47:02.746600+00:00 heroku[web.1]: State changed from up to starting
2016-10-06T01:47:05.193536+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 21226 -e production`
2016-10-06T01:47:05.457164+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-10-06T01:47:06.104876+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2016-10-06T01:47:06.105070+00:00 app[web.1]: === puma shutdown: 2016-10-06 01:47:06 +0000 ===
2016-10-06T01:47:06.105093+00:00 app[web.1]: - Goodbye!
2016-10-06T01:47:06.105295+00:00 app[web.1]: Exiting
2016-10-06T01:47:06.249906+00:00 heroku[web.1]: Process exited with status 0
2016-10-06T01:47:08.750295+00:00 app[web.1]: => Booting Puma
2016-10-06T01:47:08.750342+00:00 app[web.1]: => Rails 5.0.0.1 application starting in production on http://0.0.0.0:21226
2016-10-06T01:47:08.750343+00:00 app[web.1]: => Run `rails server -h` for more startup options
2016-10-06T01:47:08.848638+00:00 app[web.1]: DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
2016-10-06T01:47:08.848642+00:00 app[web.1]: Please use `config.public_file_server.enabled = false` instead.
2016-10-06T01:47:08.848643+00:00 app[web.1]:  (called from block in <top (required)> at /app/config/environments/production.rb:91)
2016-10-06T01:47:10.123395+00:00 app[web.1]: Puma starting in single mode...
2016-10-06T01:47:10.123408+00:00 app[web.1]: * Version 3.6.0 (ruby 2.2.4-p230), codename: Sleepy Sunday Serenity
2016-10-06T01:47:10.123409+00:00 app[web.1]: * Min threads: 5, max threads: 5
2016-10-06T01:47:10.123410+00:00 app[web.1]: * Environment: production
2016-10-06T01:47:10.123509+00:00 app[web.1]: * Listening on tcp://0.0.0.0:21226
2016-10-06T01:47:10.123829+00:00 app[web.1]: Use Ctrl-C to stop
2016-10-06T01:47:10.372515+00:00 heroku[web.1]: State changed from starting to up
2016-10-06T01:47:26.407335+00:00 heroku[api]: Starting process with command `bundle exec rake db:migrate` by hiik3n@gmail.com
2016-10-06T01:47:29.152874+00:00 heroku[run.6241]: Awaiting client
2016-10-06T01:47:29.175257+00:00 heroku[run.6241]: Starting process with command `bundle exec rake db:migrate`
2016-10-06T01:47:29.310746+00:00 heroku[run.6241]: State changed from starting to up
2016-10-06T01:47:33.081778+00:00 heroku[run.6241]: Process exited with status 0
2016-10-06T01:47:33.110064+00:00 heroku[run.6241]: State changed from up to complete
2016-10-06T01:47:56.307923+00:00 heroku[router]: at=info method=GET path="/" host=fierce-harbor-81008.herokuapp.com request_id=bfcd39c7-4f75-4745-8acb-fb25ba515dec fwd="14.169.249.198" dyno=web.1 connect=0ms service=50ms status=404 bytes=1744
2016-10-06T01:47:56.321465+00:00 app[web.1]: I, [2016-10-06T01:47:56.321375 #3]  INFO -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] Started GET "/" for 14.169.249.198 at 2016-10-06 01:47:56 +0000
2016-10-06T01:47:56.327455+00:00 app[web.1]: F, [2016-10-06T01:47:56.327159 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec]   
2016-10-06T01:47:56.327561+00:00 app[web.1]: F, [2016-10-06T01:47:56.327491 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] ActionController::RoutingError (No route matches [GET] "/"):
2016-10-06T01:47:56.328163+00:00 app[web.1]: F, [2016-10-06T01:47:56.328106 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec]   
2016-10-06T01:47:56.328328+00:00 app[web.1]: F, [2016-10-06T01:47:56.328275 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
2016-10-06T01:47:56.328838+00:00 app[web.1]: F, [2016-10-06T01:47:56.328781 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2016-10-06T01:47:56.328927+00:00 app[web.1]: F, [2016-10-06T01:47:56.328855 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
2016-10-06T01:47:56.329334+00:00 app[web.1]: F, [2016-10-06T01:47:56.329277 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
2016-10-06T01:47:56.329400+00:00 app[web.1]: F, [2016-10-06T01:47:56.329354 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
2016-10-06T01:47:56.329549+00:00 app[web.1]: F, [2016-10-06T01:47:56.329505 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-10-06T01:47:56.329658+00:00 app[web.1]: F, [2016-10-06T01:47:56.329571 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
2016-10-06T01:47:56.329714+00:00 app[web.1]: F, [2016-10-06T01:47:56.329674 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
2016-10-06T01:47:56.329797+00:00 app[web.1]: F, [2016-10-06T01:47:56.329730 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2016-10-06T01:47:56.329853+00:00 app[web.1]: F, [2016-10-06T01:47:56.329813 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
2016-10-06T01:47:56.329909+00:00 app[web.1]: F, [2016-10-06T01:47:56.329870 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
2016-10-06T01:47:56.329996+00:00 app[web.1]: F, [2016-10-06T01:47:56.329944 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-10-06T01:47:56.330067+00:00 app[web.1]: F, [2016-10-06T01:47:56.330016 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
2016-10-06T01:47:56.330361+00:00 app[web.1]: F, [2016-10-06T01:47:56.330315 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
2016-10-06T01:47:56.330639+00:00 app[web.1]: F, [2016-10-06T01:47:56.330593 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
2016-10-06T01:47:56.330706+00:00 app[web.1]: F, [2016-10-06T01:47:56.330659 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
2016-10-06T01:47:56.330808+00:00 app[web.1]: F, [2016-10-06T01:47:56.330724 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
2016-10-06T01:47:56.331035+00:00 app[web.1]: F, [2016-10-06T01:47:56.330964 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
2016-10-06T01:47:56.331101+00:00 app[web.1]: F, [2016-10-06T01:47:56.331054 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
2016-10-06T01:47:56.331412+00:00 app[web.1]: F, [2016-10-06T01:47:56.331344 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
2016-10-06T01:47:56.331478+00:00 app[web.1]: F, [2016-10-06T01:47:56.331435 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
Lams-MacBook-Pro:myblog lamdo$ 
```

Do you have ant comment about this log?
My steps when deploying to heroku: Stop rail server,Commit to Heroku master (create push, db migrate,..)
Thank you for your help

## Lam

**Comment by hiik3n** [comment]
@coderschoolreview 
problem maybe arround
`2016-10-06T01:47:56.307923+00:00 heroku[router]: at=info method=GET path="/" host=fierce-harbor-81008.herokuapp.com request_id=bfcd39c7-4f75-4745-8acb-fb25ba515dec fwd="14.169.249.198" dyno=web.1 connect=0ms service=50ms status=404 bytes=1744
2016-10-06T01:47:56.321465+00:00 app[web.1]: I, [2016-10-06T01:47:56.321375 #3]  INFO -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] Started GET "/" for 14.169.249.198 at 2016-10-06 01:47:56 +0000
2016-10-06T01:47:56.327455+00:00 app[web.1]: F, [2016-10-06T01:47:56.327159 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec]   
2016-10-06T01:47:56.327561+00:00 app[web.1]: F, [2016-10-06T01:47:56.327491 #3] FATAL -- : [bfcd39c7-4f75-4745-8acb-fb25ba515dec] ActionController::RoutingError (No route matches [GET] "/"):`

but I do not know how to fix!

**Comment by AlecksJohanssen** [comment]
Hi @hiik3n Could you please join https://gitter.im/coderschool/prework It will be easy for 2 of us to chat. and It wil lbe quicker

**Comment by AlecksJohanssen** [comment]
Hi @hiik3n seems like you haven't set the root . You can learn more about root here `http://guides.rubyonrails.org/routing.html#using-root`

**Comment by hiik3n** [comment]
@coderschoolreview ,@AlecksJohanssen Thanks for your suggestion. 
But in the evening I can not connect to heroku api (same as last night):
`ENOTFOUND: getaddrinfo ENOTFOUND api.heroku.com api.heroku.com:443`
Do you meet this frequently? I meet it a lot!

**Comment by hiik3n** [comment]
@coderschoolreview I tried add root so It worked. However, the delete feature does not working as it in localhost!! Do you have any idea?
Thanks.

**Comment by coderschoolreview** [comment]
@hiik3n, try to add `//=require tether` in `application.js` to see if it work

**Comment by coderschoolreview** [comment]
@hiik3n how did it go? I can see that you haven't included the tether gem in your Gemfile, this is a prerequisite to make delete work on Heroku, [click here](https://github.com/twbs/bootstrap-rubygem) to read more.
--  
Thomas

**Comment by hiik3n** [comment]
@coderschoolreview It works now, Thank you so much 💃

**Comment by hiik3n** [comment]
@coderschoolreview I am trying to implement other feature.
I do not understand "responsive to window size". I just add navbar?

**Comment by hiik3n** [comment]
@coderschoolreview I faced issue of migrating db in local to heroku. I has migrated successfully db in local (add column view_count), app run well, but when I push to heroku and do db:migrate, the db on heroku seem not know new column. 
Thanks.
